-- MySQL Script generated by MySQL Workbench
-- Πεμ 29 Δεκ 2022 11:07:39 μμ EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`undergraduates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`undergraduates` ;

CREATE TABLE IF NOT EXISTS `mydb`.`undergraduates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `university` VARCHAR(45) NOT NULL,
  `marks` BLOB NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`companies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `town` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `street_number` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`internship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`internship` ;

CREATE TABLE IF NOT EXISTS `mydb`.`internship` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `field` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  `duration` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `espa` TINYINT NOT NULL,
  `salary` INT NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `companies_id` INT NOT NULL,
  `undergraduates_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_internship_companies1_idx` (`companies_id` ASC) VISIBLE,
  INDEX `fk_internship_undergraduates1_idx` (`undergraduates_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_internship_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `mydb`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_internship_undergraduates1`
    FOREIGN KEY (`undergraduates_id`)
    REFERENCES `mydb`.`undergraduates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`undergraduates_has_internship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`undergraduates_has_internship` ;

CREATE TABLE IF NOT EXISTS `mydb`.`undergraduates_has_internship` (
  `internship_id` INT NOT NULL,
  `undergraduates_id` INT NOT NULL,
  `internship_companies_id` INT NOT NULL,
  PRIMARY KEY (`internship_id`),
  INDEX `fk_undergraduates_has_internship_internship1_idx` (`internship_id` ASC, `internship_companies_id` ASC) VISIBLE,
  INDEX `fk_undergraduates_has_internship_undergraduates1_idx` (`undergraduates_id` ASC) VISIBLE,
  CONSTRAINT `fk_undergraduates_has_internship_undergraduates1`
    FOREIGN KEY (`undergraduates_id`)
    REFERENCES `mydb`.`undergraduates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_undergraduates_has_internship_internship1`
    FOREIGN KEY (`internship_id` , `internship_companies_id`)
    REFERENCES `mydb`.`internship` (`id` , `companies_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
